#!/usr/bin/env python3
"""
bifilar_near_field.py
=====================

Source-of-truth Python script for the figures and numerical-example table
referenced by `docs/derivations/bifilar_near_field_enhancement.md`.

Run:
    python3 notebooks/bifilar_near_field.py

Outputs (relative to repo root):
    docs/field-notes/volume-1/figures/fig04_bifilar_enhancement.png
    docs/field-notes/volume-1/figures/fig04_bifilar_enhancement.pdf

Also prints the numerical-example table to stdout in markdown-compatible form,
so the derivation doc's table can be regenerated by copy-paste.

Reproducibility: this file is the canonical source. The paired Jupyter
notebook `bifilar_near_field.ipynb` is generated from it; if the two disagree,
the .py file wins.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Geometry constants. Match docs/derivations/bifilar_near_field_enhancement.md.
# ---------------------------------------------------------------------------
MU_0 = 4.0 * math.pi * 1.0e-7        # H/m, vacuum permeability
A = 0.050                            # m, loop radius (5 cm)
D = 0.005                            # m, axial separation (5 mm) -> d/a = 0.10
I = 0.050                            # A, loop current (50 mA)


# ---------------------------------------------------------------------------
# Closed-form fields from the derivation.
# ---------------------------------------------------------------------------
def b_single_loop(r: np.ndarray, a: float = A, current: float = I) -> np.ndarray:
    """Eq. (1): on-axis B of a single circular loop at distance r from its centre."""
    return (MU_0 * current * a**2) / (2.0 * (a**2 + r**2) ** 1.5)


def b_bifilar_exact(r: np.ndarray, a: float = A, d: float = D,
                    current: float = I) -> np.ndarray:
    """Eq. (2): exact superposition of upper (+I @ +d/2) and lower (-I @ -d/2) loops."""
    coeff = (MU_0 * current * a**2) / 2.0
    upper = 1.0 / (a**2 + (r - d / 2.0) ** 2) ** 1.5
    lower = 1.0 / (a**2 + (r + d / 2.0) ** 2) ** 1.5
    return coeff * (upper - lower)


def eta_b_leading(r: np.ndarray, a: float = A, d: float = D) -> np.ndarray:
    """Eq. (7): leading-order on-axis enhancement factor 3 d r / (a^2 + r^2)."""
    return 3.0 * d * r / (a**2 + r**2)


# ---------------------------------------------------------------------------
# Numerical-example table for the derivation doc.
# ---------------------------------------------------------------------------
def print_numerical_table() -> None:
    rows_r = np.array([0.01, A / 2.0, A, 2.0 * A, 4.0 * A])
    labels = ["1 cm", "a/2 = 2.5 cm", "a = 5 cm", "2a = 10 cm", "4a = 20 cm"]

    eta_lead = eta_b_leading(rows_r)
    b_ref = b_single_loop(rows_r)
    b_bif = b_bifilar_exact(rows_r)
    eta_exact = np.abs(b_bif / b_ref)

    print("\n## Numerical-example table (regenerate by running this script)\n")
    header = (
        "| r | eta_B (leading) | eta_B (exact) | |B_bif| | |B_ref| |"
    )
    sep = "|---|---|---|---|---|"
    print(header)
    print(sep)
    for label, et_l, et_e, bb, br in zip(labels, eta_lead, eta_exact, b_bif, b_ref):
        print(
            f"| {label} | {et_l:.4f} | {et_e:.4f} "
            f"| {fmt_field(abs(bb))} | {fmt_field(br)} |"
        )
    # Maximum point — analytic prediction: eta_max = 3 d / (2 a) at r = a.
    eta_max_analytic = 3.0 * D / (2.0 * A)
    print(f"\nAnalytic eta_max = 3 d / (2 a) = {eta_max_analytic:.4f}  (at r = a)")
    # Sanity check: leading-order matches at r = a.
    assert abs(eta_b_leading(np.array([A]))[0] - eta_max_analytic) < 1e-12


def fmt_field(value_tesla: float) -> str:
    """Pretty-print B in nT or uT, matching the derivation doc table."""
    if value_tesla >= 1.0e-6:
        return f"{value_tesla * 1.0e6:.3f} uT"
    return f"{value_tesla * 1.0e9:.2f} nT"


# ---------------------------------------------------------------------------
# Figure 4 of Field Notes Vol. I: on-axis enhancement factor.
# ---------------------------------------------------------------------------
def make_fig04(out_dir: Path) -> None:
    r_over_a = np.geomspace(1.0e-2, 1.0e1, 800)
    r = r_over_a * A

    eta_lead = eta_b_leading(r)
    b_bif = b_bifilar_exact(r)
    b_ref = b_single_loop(r)
    eta_exact = np.abs(b_bif / b_ref)

    fig, ax = plt.subplots(figsize=(6.4, 4.2), dpi=140)
    ax.plot(r_over_a, eta_lead, lw=2.0, label=r"Leading order: $3 d r / (a^2 + r^2)$")
    ax.plot(r_over_a, eta_exact, lw=1.2, ls="--",
            label="Exact (eq. 2 / eq. 6)")
    # Maximum point.
    eta_max = 3.0 * D / (2.0 * A)
    ax.scatter([1.0], [eta_max], s=40, color="C3", zorder=5,
               label=fr"Maximum at $r = a$, $\eta_B^{{\max}} = 3d/(2a) = {eta_max:.3f}$")
    # Reference line at eta = 1 (where bifilar would match a single loop).
    ax.axhline(1.0, color="0.4", lw=0.8, ls=":", label=r"$\eta_B = 1$ (parity with single loop)")

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel(r"$r / a$  (on-axis distance, normalized to loop radius)")
    ax.set_ylabel(r"$\eta_B(r) = |B_z^{\mathrm{bif}}| / |B_z^{\mathrm{ref}}|$")
    ax.set_title(
        r"Series-opposing bifilar on-axis field, normalized to single loop"
        + "\n"
        + fr"($a = {A * 1e2:.0f}\,$cm, $d = {D * 1e3:.0f}\,$mm, $d/a = {D/A:.2f}$)",
        fontsize=11,
    )
    ax.grid(True, which="both", ls=":", lw=0.5, alpha=0.7)
    ax.legend(loc="lower center", fontsize=8, framealpha=0.95)
    ax.set_xlim(1.0e-2, 1.0e1)
    ax.set_ylim(1.0e-4, 2.0)

    fig.tight_layout()
    out_png = out_dir / "fig04_bifilar_enhancement.png"
    out_pdf = out_dir / "fig04_bifilar_enhancement.pdf"
    fig.savefig(out_png, dpi=200)
    fig.savefig(out_pdf)
    plt.close(fig)
    print(f"\nWrote {out_png.relative_to(REPO_ROOT)}")
    print(f"Wrote {out_pdf.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Reproducibility footer.
# ---------------------------------------------------------------------------
def print_reproducibility_footer() -> None:
    import platform
    import scipy
    print("\n## Reproducibility\n")
    print(f"- python    : {platform.python_version()}")
    print(f"- numpy     : {np.__version__}")
    print(f"- scipy     : {scipy.__version__}")
    print(f"- matplotlib: {plt.matplotlib.__version__}")
    print(f"- platform  : {platform.platform()}")


# ---------------------------------------------------------------------------
# Entry point.
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
FIG_DIR = REPO_ROOT / "docs" / "field-notes" / "volume-1" / "figures"


def main() -> int:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    print_numerical_table()
    make_fig04(FIG_DIR)
    print_reproducibility_footer()
    return 0


if __name__ == "__main__":
    sys.exit(main())
