#!/usr/bin/env -S blender --background --python
"""
build_crown_shell_r1.py — parametric generator for HelmKit Mk0.5 R1.

Builds `crown_shell_R1.stl`: the forward 220° crown band that carries
the integral curved Picatinny rail and the hardpoint stations.

Run:
    blender --background --python tools/blender/build_crown_shell_r1.py \\
        -- --out 3D-Models/HelmKit/_generated/crown_shell_R1.stl

Design canon (do not change without updating
docs/mechanical/mk0.5_base_crown_architecture.md):
    - R1 inner radius:      95.0 mm
    - R1 wall thickness:    3.0  mm  (PETG, 0.2 mm layer, X-MAX3)
    - R1 forward arc:       220° (centered on forehelm; HP-F = 0°)
    - R1 vertical height:   45   mm
    - Rail tooth pitch:     5.0  mm  (MIL-STD-1913)
    - Rail top width:       10.2 mm
    - Rail bottom width:    19.0 mm
    - Rail slot width:      5.55 mm
    - Rail tooth depth:     3.4  mm
    - Rail recoil-shoulder: 45°
    - Rail Z position:      mid-band (centerline at R1.z = 0)

License provenance:
    Tooth cross-section dimensions come from MIL-STD-1913, which is a
    US-government public specification. The cross-section used here is
    informed by — but not copied from — Thingiverse #23185 by SFE_Tim
    (CC-BY 4.0), staged at:
        3D-Models/HelmKit/_derived/picatinny_rail_23185_SFE_Tim/
    The geometry generated by this script is original HelmKit work
    (sweep of a measured profile along a novel curved path), released
    under HelmKit's repo license. SFE_Tim's contribution is acknowledged
    per CC-BY in ATTRIBUTIONS.md.

Status: SCAFFOLD. Generates correct R1 shell + rail topology but has
not yet been validated against G-Print / G-Fit gates.
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

try:
    import bpy  # type: ignore
    import bmesh  # type: ignore
    from mathutils import Vector  # type: ignore
except ImportError:
    print("ERROR: this script must be run inside Blender:")
    print("  blender --background --python tools/blender/build_crown_shell_r1.py")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Canon parameters
# ---------------------------------------------------------------------------

# Crown band
R1_INNER_RADIUS_MM = 95.0
R1_WALL_MM = 3.0
R1_ARC_DEG = 220.0
R1_HEIGHT_MM = 45.0

# Picatinny tooth (MIL-STD-1913)
TOOTH_PITCH_MM = 5.0
TOOTH_TOP_W_MM = 10.2
TOOTH_BOT_W_MM = 19.0  # NOT used in 2D profile; for full-rail body if drawn
SLOT_W_MM = 5.55
TOOTH_DEPTH_MM = 3.4
SHOULDER_ANGLE_DEG = 45.0

# Rail mounting on R1
RAIL_Z_OFFSET_MM = 0.0     # mid-band
RAIL_ARC_DEG = 200.0       # rail covers 200° of the 220° arc, leaving 10° lead-in at each end


# ---------------------------------------------------------------------------
# Mesh helpers
# ---------------------------------------------------------------------------

def reset_scene() -> None:
    """Wipe the default scene so the script is idempotent."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in (bpy.data.meshes, bpy.data.curves, bpy.data.objects):
        for item in list(block):
            block.remove(item)


def make_band_R1() -> bpy.types.Object:
    """Build the R1 crown band as a 220° arc segment of an annular cylinder."""
    bpy.ops.mesh.primitive_cylinder_add(
        radius=R1_INNER_RADIUS_MM + R1_WALL_MM,
        depth=R1_HEIGHT_MM,
        vertices=256,
    )
    outer = bpy.context.active_object
    outer.name = "R1_outer"

    bpy.ops.mesh.primitive_cylinder_add(
        radius=R1_INNER_RADIUS_MM,
        depth=R1_HEIGHT_MM + 2.0,  # slight overshoot for clean boolean
        vertices=256,
    )
    inner = bpy.context.active_object
    inner.name = "R1_inner"

    # Boolean: outer - inner = annulus
    mod = outer.modifiers.new(name="annulus", type="BOOLEAN")
    mod.operation = "DIFFERENCE"
    mod.object = inner
    bpy.context.view_layer.objects.active = outer
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(inner, do_unlink=True)

    # Cut a 360° - 220° = 140° wedge out of the back to leave the forward 220° arc
    wedge_angle = math.radians(360.0 - R1_ARC_DEG)
    bpy.ops.mesh.primitive_cylinder_add(
        radius=R1_INNER_RADIUS_MM + R1_WALL_MM + 5.0,
        depth=R1_HEIGHT_MM + 2.0,
        vertices=4,  # we'll bmesh-edit this into a wedge below
    )
    cutter = bpy.context.active_object
    cutter.name = "R1_back_cutter"
    # Replace with a true wedge mesh
    bm = bmesh.new()
    apex = bm.verts.new((0, 0, -(R1_HEIGHT_MM + 1) / 2))
    apex_top = bm.verts.new((0, 0, +(R1_HEIGHT_MM + 1) / 2))
    r = R1_INNER_RADIUS_MM + R1_WALL_MM + 5.0
    n = 32
    # Wedge centered on -Y (back of helmet); HP-F is at +Y
    a0 = math.pi / 2 + math.radians(R1_ARC_DEG) / 2  # rightmost back edge
    a1 = math.pi / 2 - math.radians(R1_ARC_DEG) / 2 + 2 * math.pi
    ring_bot = []
    ring_top = []
    for i in range(n + 1):
        t = i / n
        a = a0 + t * (a1 - a0 - 2 * math.pi + 2 * math.pi)  # sweep the back 140°
        # Actually simpler: sweep from a0 around through -Y to a1' = a0 + (360-arc) deg
        a = a0 + t * math.radians(360.0 - R1_ARC_DEG)
        x = r * math.cos(a)
        y = r * math.sin(a)
        ring_bot.append(bm.verts.new((x, y, -(R1_HEIGHT_MM + 1) / 2)))
        ring_top.append(bm.verts.new((x, y, +(R1_HEIGHT_MM + 1) / 2)))
    # faces
    for i in range(n):
        bm.faces.new((apex, ring_bot[i + 1], ring_bot[i]))
        bm.faces.new((apex_top, ring_top[i], ring_top[i + 1]))
        bm.faces.new((ring_bot[i], ring_bot[i + 1], ring_top[i + 1], ring_top[i]))
    bm.faces.new((apex, apex_top, ring_top[0], ring_bot[0]))
    bm.faces.new((apex_top, apex, ring_bot[-1], ring_top[-1]))
    bm.to_mesh(cutter.data)
    bm.free()

    mod = outer.modifiers.new(name="cut_back", type="BOOLEAN")
    mod.operation = "DIFFERENCE"
    mod.object = cutter
    bpy.context.view_layer.objects.active = outer
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(cutter, do_unlink=True)

    outer.name = "crown_shell_R1"
    return outer


def make_picatinny_tooth_profile() -> list[tuple[float, float]]:
    """Return the 2D cross-section of one Picatinny tooth as (x, z) pairs.

    Coordinates are in the (radial, vertical) plane that will be swept
    tangent to R1's outer surface. Origin = base of the rail (sits on
    the outer skin of R1). +x = outward (radial); +z = up.
    """
    # Trapezoidal tooth: bottom wider, top narrower (dovetail).
    # Profile (one full pitch unit, viewed from rail side):
    #     top edge       _______________
    #                   /               \
    #                  /                 \
    #     shoulder    /                   \
    #                /                     \
    #     slot floor ‾‾‾                 ‾‾‾
    # We model HALF a pitch (a single tooth + adjacent slot wall).
    # Since we sweep this around the helmet, the geometry repeats.
    # For now: return the FULL rail-body cross-section (a single 2D
    # polygon that, when revolved tangentially, gives the rail beam).
    h = TOOTH_DEPTH_MM
    top = TOOTH_TOP_W_MM / 2
    bot = TOOTH_BOT_W_MM / 2  # widens at base
    # Sweep along R1, so the "length" axis is tangential. For a 2D
    # cross-section in the radial-vertical plane:
    #   - Width (z) = TOOTH_TOP_W_MM at top, TOOTH_BOT_W_MM at base
    #   - Height (x, outward) = TOOTH_DEPTH_MM above the R1 skin
    profile = [
        (0.0, -bot),  # base, lower-left (against R1 outer skin)
        (0.0, +bot),  # base, upper-left
        (h, +top),    # top, upper-right (dovetail in-slope)
        (h, -top),    # top, lower-right
    ]
    return profile


def make_curved_rail() -> bpy.types.Object:
    """Sweep the Picatinny cross-section along R1's outer-skin arc.

    The TOOTH slots (perpendicular cuts every TOOTH_PITCH_MM along the
    arc) are subtracted in a second pass.
    """
    # Step 1: build the rail BODY as a swept arc
    arc_rad = math.radians(RAIL_ARC_DEG)
    r_skin = R1_INNER_RADIUS_MM + R1_WALL_MM
    n_seg = 240  # arc segments
    bm = bmesh.new()
    profile = make_picatinny_tooth_profile()
    rings = []
    for i in range(n_seg + 1):
        t = i / n_seg
        # Center the rail on +Y (HP-F = 0° = +Y in our convention here)
        a = math.pi / 2 + (t - 0.5) * arc_rad
        cos_a, sin_a = math.cos(a), math.sin(a)
        ring = []
        for (h_out, z_off) in profile:
            r = r_skin + h_out
            x = r * cos_a
            y = r * sin_a
            z = RAIL_Z_OFFSET_MM + z_off
            ring.append(bm.verts.new((x, y, z)))
        rings.append(ring)
    # Stitch rings into faces
    P = len(profile)
    for i in range(n_seg):
        for j in range(P):
            j2 = (j + 1) % P
            bm.faces.new((rings[i][j], rings[i + 1][j], rings[i + 1][j2], rings[i][j2]))
    # End caps
    bm.faces.new(rings[0][::-1])
    bm.faces.new(rings[-1])
    mesh = bpy.data.meshes.new("rail_body_mesh")
    bm.to_mesh(mesh)
    bm.free()
    rail = bpy.data.objects.new("curved_rail_body", mesh)
    bpy.context.collection.objects.link(rail)

    # Step 2: TODO — subtract tooth slots (boolean a series of thin
    # rectangular cutters every TOOTH_PITCH_MM along the arc).
    # Marked as a known gap; see G-Print acceptance gate in
    # docs/mechanical/mk0.5_base_crown_architecture.md.

    return rail


def union(a: bpy.types.Object, b: bpy.types.Object) -> bpy.types.Object:
    mod = a.modifiers.new(name=f"union_{b.name}", type="BOOLEAN")
    mod.operation = "UNION"
    mod.object = b
    bpy.context.view_layer.objects.active = a
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(b, do_unlink=True)
    return a


def export_stl(obj: bpy.types.Object, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    # Blender 4.x+/5.x: wm.stl_export. Fallback to legacy export_mesh.stl.
    if hasattr(bpy.ops.wm, "stl_export"):
        bpy.ops.wm.stl_export(filepath=str(out_path), export_selected_objects=True)
    else:
        bpy.ops.export_mesh.stl(filepath=str(out_path), use_selection=True)
    print(f"Wrote {out_path} ({out_path.stat().st_size} bytes)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    # Strip Blender's own argv up to the "--"
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1 :]
    else:
        argv = []
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, required=True, help="Output STL path")
    args = p.parse_args(argv)

    reset_scene()
    shell = make_band_R1()
    rail = make_curved_rail()
    combined = union(shell, rail)
    export_stl(combined, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
